modifying as ready
marqo-ai/py-marqo pull request #157
Opened 2023-08-13 08:49 UTC by danyilq

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- cloud instance mapping now takes modifying as ready

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2023-08-13 14:08 UTC, farshidz requested changes, later dismissed

2023-08-13 14:08 UTC, farshidz commented on src/marqo/marqo_cloud_instance_mappings.py
> +            if index.get('index_status') in [IndexStatus.READY, IndexStatus.MODIFYING]:
The enum `IndexStatus` is a nice touch but it's not used consistently. It would be good to use it everywhere that `_urls_mapping` is accessed.  e.g. line 29 this file

2023-08-13 14:08 UTC, farshidz commented on tests/v0_tests/test_marqo_cloud_instance_mapping.py
> +    def test_modifying_state_returns_as_ready(self, mock_get):
Please test all five cloud states (creating, ready, modifying, deleting, deleted) are handled appropriately. This covers modifying so four more to test.

2023-08-13 14:08 UTC, farshidz commented on src/marqo/marqo_cloud_instance_mappings.py
> +            elif index.get('index_status') == IndexStatus.CREATING:
Please add state transition tests for this function. i.e. creating -> ready, ready -> deleting/deleted, ready->modifying, modifying->ready. In each test ensure mappings are left in a valid state. I suspect currently creating->ready won't clean up the record from Creating, which looking at the rest of the code won't break anything currently but is a risk and should be addressed.

2023-08-13 23:24 UTC, pandu-k commented on tests/v0_tests/test_marqo_cloud_instance_mapping.py
@danyilq lets include assertions about expected log statements

2023-08-14 01:33 UTC, pandu-k commented on src/marqo/enums.py
Remember to bump version

2023-08-14 01:33 UTC, pandu-k commented on tests/v0_tests/test_marqo_cloud_instance_mapping.py
1. Add test for asserting search only does 1 HTTP Requests most of the time
2. Add test for asserting search only does 2 HTTP Requests when cache is refreshing
3. Add some assert `mock_get.called_x` times in the following tests

2023-08-14 02:33 UTC, pandu-k approved these changes

2023-08-14 02:35 UTC, merged