Li/version check
marqo-ai/py-marqo pull request #209
Opened 2024-01-11 03:59 UTC by wanliAlex

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
We recommend marqo1 if we detect the marqo version is 1.x.x

* **What is the current behavior?** (You can also link to an open issue here)
we don't have marqo1 recommendation

* **What is the new behavior (if this is a feature change)?**
We recommend marqo1 if we detect the marqo version is 1.x.x

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
no

* **Other information**:
no

2024-01-12 00:47 UTC, farshidz requested changes

2024-01-12 00:47 UTC, farshidz commented on src/marqo/index.py
> +                        f"If you intended to use Marqo versions 1.x.x, "
If you intended to use Marqo 1.x, please use Python client 2.x (pip install marqo==2).

2024-01-12 00:47 UTC, farshidz commented on src/marqo/index.py
> +                        f"please restart your Marqo client Python interpreter.")
please restart your Python interpreter.

2024-01-12 00:47 UTC, farshidz commented on src/marqo/index.py
> +                                      f"please restart your Marqo client Python interpreter.")
please restart your Python interpreter.

2024-01-12 02:30 UTC, pandu-k commented on src/marqo/index.py
> +                        f"please use the 'marqo1' Python client by pip install marqo1. "
```
please use the 'marqo1' Python client by pip install marqo1. 
```
->
```
please use the 'marqo1' Python client: `pip install marqo1`
```

2024-01-17 12:34 UTC, farshidz approved these changes

2024-01-17 23:24 UTC, merged