Always cleanup cloud indexes from tests
marqo-ai/py-marqo pull request #251
Opened 2024-09-10 06:58 UTC by vicilliar

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix

* **What is the current behavior?** (You can also link to an open issue here)
When cloud integration test run is cancelled, indexes are not cleaned up.

* **What is the new behavior (if this is a feature change)?**
Cleans up indexes regardless of outcome of integration test.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:

2024-09-18 07:17 UTC, vicilliar commented
Proof that script will only clean up associated indexes (for this run).
- Only 2 indexes are attempting to be deleted, even if 7 are present in the account.
- Constantly waits for indexes to be READY or FAILED before sending delete request again. 30s sleep confirmed.
<img width="1136" alt="image" src="https://github.com/user-attachments/assets/31b888c2-113e-4348-bc19-afde24aa34e3">

2024-09-18 07:25 UTC, vicilliar commented
Test cases needed:
- 1 smooth successful run, with cleanup

2024-09-19 00:54 UTC, vicilliar commented
1 Full Test run cancelled (5 indices deleted by cleanup script)
Run: https://github.com/marqo-ai/py-marqo/actions/runs/10917619817/job/30301648628
~37 minutes to delete all (including waiting for index to disappear from list
![image](https://github.com/user-attachments/assets/2a7008c5-c9a6-491a-8908-878190340e34)

2024-09-19 00:56 UTC, vicilliar commented
Cancel run with no indexes to delete:
![image](https://github.com/user-attachments/assets/6bb81618-ff9d-4cec-bc78-96c5ba7f11b2)

2024-09-19 01:59 UTC, vicilliar commented
Concurrency check (only 1 run is allowed at a time)
![image](https://github.com/user-attachments/assets/2baaa4a5-bfdc-4d44-9012-8b92f951ab6f)
![image](https://github.com/user-attachments/assets/990d021c-55c2-4482-932f-c1d3a853fc09)

Works as intended.

2024-09-19 02:29 UTC, vicilliar commented
Workflow TIMEOUT: After hitting 1 hour, with tests being stuck at `test_config.py`, entire test job failed out.
Then Cleanup cloud indexes job was run automatically. This is intended behavior.
![image](https://github.com/user-attachments/assets/265348a4-bf1f-4e53-8fb7-01f32552ab01)

Will investigate why tests were stuck at `test_config.py`

2024-09-20 05:17 UTC, wanliAlex requested changes

2024-09-20 05:17 UTC, wanliAlex commented on .github/workflows/cloud-integration-tests.yml
>        - name: Install dependencies
Is this step still necessary after the `pip install -e .`?

2024-09-20 07:13 UTC, vicilliar commented on .github/workflows/cloud-integration-tests.yml
>        - name: Install dependencies
Yep! `pip install -e .` just installs py-marqo, but the `requirements.txt` file has other packages

2024-09-23 05:37 UTC, wanliAlex approved these changes

2024-09-24 00:46 UTC, merged